# Generated by Django 3.1.2 on 2020-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
                ('display_image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('display_images_url', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Combo_Mashup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('display_images_url', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_combo', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('categories', models.ManyToManyField(blank=True, to='menues.Category')),
                ('combos', models.ManyToManyField(blank=True, to='menues.Combo')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_items',
            field=models.ManyToManyField(blank=True, to='menues.Combo_Mashup'),
        ),
    ]
